language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "devus10"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - ./gradlew sonarqube