dictionary-target-directory: dictionaries

dictionary:
  polish:
    target-dir: ${dictionary-target-directory}/polish
    sjp:
      url: https://sjp.pl/slownik/odmiany
  english:
    math-sjsu-edu:
      url: http://www.math.sjsu.edu/~foster/dictionary.txt
