dictionary-target-directory:

dictionary-saving-cron:

dictionary:
  polish:
    target-dir:
    sjp:
      url:
  english:
    math-sjsu-edu:
      url:

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:

hardware:
  cpus: