dictionary-target-directory: dictionaries

dictionary-saving-cron: "0 0 0 * * SAT" # = every saturday midnight

dictionary:
  polish:
    target-dir: ${dictionary-target-directory}/polish
    sjp:
      url: https://sjp.pl/slownik/odmiany/
  english:
    math-sjsu-edu:
      url: http://www.math.sjsu.edu/~foster/dictionary.txt

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wordfinder
    username: postgres
    password: 889
  jpa:
    hibernate:
      ddl-auto: validate

hardware:
  cpus: 4