apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordfinder
  labels:
    app: wordfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordfinder
  template:
    metadata:
      labels:
        app: wordfinder
    spec:
      containers:
      - name: wordfinder
        image: localhost:32000/words-finder
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: wordfinder-config
---
apiVersion: v1
kind: Service
metadata:
  name: wordfinder
spec:
  type: NodePort
  selector:
    app: wordfinder
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      nodePort: 30008
